image:
  tag: v0.1.3
replicas: 1
ports:
  containerPort: 8080

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30001

ingress:
  host: shop.yab.dev.tap.telekom.de
  backendPort: 80
 
