apiVersion: v1
kind: Service
metadata:
  name: nginx-stats
  labels:
    app: nginx-exporter
    service: nginx    
spec:
  selector:
    app: nginx
  ports:
    - name: exporter
      port: 9113
      targetPort: 9113